### ISSUE TITLE
[Stepping] skips statements in a loop inside of original file

### ISSUE THREAD

**Issue by yurydelendik** [firefox-devtools/debugger#4113]
STR:
1. Open [sequence_print][sp]
2. Set breakpoint at line 4 (`buffer.push(current);`) of the "sequence_print.js" file
3. Reload the page
4. Click "Step in" button

Actual:
Debugger skipped loop

Expected:
Debugger stayed on the line 4 for seven more times.

[sp]: http://firefox-dev.tools/debugger-examples/examples/sequence-print/sequence_print.html

**Comment by jasonLaster** [comment]
Here is the source map [visualization][v]. It looks fine. Could this be an issue w/ column stepping?

[v]: https://sokra.github.io/source-map-visualization/#base64,ZnVuY3Rpb24gc2VxdWVuY2VQcmludChuLHIpe2Zvcih2YXIgZT1bXSx1PW47dTw9cjt1KyspZS5wdXNoKHUpO3JldHVybiBlLmpvaW4oIiwiKX0KLy8jIHNvdXJjZU1hcHBpbmdVUkw9c2VxdWVuY2VfcHJpbnQubWluLmpzLm1hcAo=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNlcXVlbmNlX3ByaW50LmpzIl0sIm5hbWVzIjpbInNlcXVlbmNlUHJpbnQiLCJmcm9tIiwidG8iLCJidWZmZXIiLCJjdXJyZW50IiwicHVzaCIsImpvaW4iXSwibWFwcGluZ3MiOiJBQUFBLFNBQVNBLGNBQWNDLEVBQU1DLEdBRTNCLElBQUssSUFEREMsS0FDS0MsRUFBVUgsRUFBTUcsR0FBV0YsRUFBSUUsSUFDdENELEVBQU9FLEtBQUtELEdBRWQsT0FBT0QsRUFBT0csS0FBSyIsImZpbGUiOiJleGFtcGxlLmpzIn0=,ZnVuY3Rpb24gc2VxdWVuY2VQcmludChmcm9tLCB0bykgewogIHZhciBidWZmZXIgPSBbXTsKICBmb3IgKHZhciBjdXJyZW50ID0gZnJvbTsgY3VycmVudCA8PSB0bzsgY3VycmVudCsrKSB7CiAgICBidWZmZXIucHVzaChjdXJyZW50KTsKICB9CiAgcmV0dXJuIGJ1ZmZlci5qb2luKCcsJyk7Cn0K

**Comment by jasonLaster** [comment]
This is an issue that pause points would fix. The reason that it does not work in this case is that we only get the pause points for the selected source, which by default is the original source. There are two ways to prove this:

1. go to https://married-coach.glitch.me/, which has a minified example and just step in
2. view both the minified and original file in the example


Next steps, we should either: 
1. get pause points for generated files
2. sourcemap pause points

### pause points because there are no sourcemaps

![](http://g.recordit.co/tEslp2YTqI.gif)

### pause points via viewing minified file

![](http://g.recordit.co/4n4BjyRXil.gif)

**Comment by jasonLaster** [comment]
This is similar to #6761 and #6835

**Comment by janodvarko** [comment]
I believe that this is fixed, I am able to nicely step through the cycles.
And in minified script (one line) I am nicely seeing Col BPs and moving between them!

If you see the problem again, please report a new bug in Bugzilla
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
