### ISSUE TITLE
[prepush] Prepush script does not run on windows machines

### ISSUE THREAD

**Issue by atwalg2** [firefox-devtools/debugger#5164]
Steps to reproduce:
* Use windows machine
* Run git push on gitbash or bash on windows

![image](https://user-images.githubusercontent.com/23143862/35195501-8d12f194-fe92-11e7-9ca1-1adbb97dd67f.png)

I am working around it by appending the windows command "start".
![image](https://user-images.githubusercontent.com/23143862/35195529-05d81be0-fe93-11e7-87b6-1f1d3c461a3c.png)

-----------------------------------------------

**Comment by julienw** [comment]
I think the issue is with running node in git bash. ([we're not alone](https://stackoverflow.com/questions/35820422/unknown-stdin-file-type-error-in-windows#36422432) but I found nothing on node's github)

I think another workaround is adding "start" before your "git push" command.

I'd be interested to know:
* how you installed node
* if you have the same issue when running in a plain command prompt (not in bash)

Thanks !

**Comment by atwalg2** [comment]
Works fine in Powershell/Command Prompt. I think it is just a gitbash/bash on windows problem.

**Comment by julienw** [comment]
And how did you install node, please ? So that we can try to reproduce as close to your environment as possible.

**Comment by atwalg2** [comment]
I installed node 9.4 originally via bash on linux with -g. I don't remember
the exact script for that. When using PowerShell/gitbash I just installed
mode 9. 4 by installing the executable for Windows machines from the node
website.

**Comment by jasonLaster** [comment]
Ping @julienw @atwalg2 @Garbee @darkwing  do you think you could  help with this?

**Comment by darkwing** [comment]
I'll check this out tonight or tomorrow morning!

**Comment by julienw** [comment]
I think there's nothing to do on our end, as the bug is either in node or in gitbash. A workaround is, i think,  that the user runs `start git push` instead of just `git push` (I haven't tried the workaround myself). I don't think we should (if we even can!) work around these environment issues in our project.

**Comment by jasonLaster** [comment]
got it, yeah maybe our fix is just improvements to the docs. Like suggesting `start git push`

**Comment by bomsy** [comment]
No longer needed after move to MC
