### ISSUE TITLE
Review icon used for node reps

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6151]
_From @nchevobbe on June 5, 2017 12:59_

_Moved from https://github.com/devtools-html/reps/issues/106_

The icon currently used for node reps can be confusing.

![image](https://cloud.githubusercontent.com/assets/1141550/23514913/088da7d0-ff69-11e6-9224-57f7725a963e.png)

- in the old console this icon acts as an element picker
- in the ruleview and animation inspector, the icon acts as a highlighter

We should settle on one icon for picking elements and one icon for highlighting.

_Copied from original issue: devtools-html/devtools-core#403_

**Comment by fvsch** [comment]
@nchevobbe I tend to agree. Should we move this issue to the ux repo, since it's a cross-tool design issue, or maybe add a ux label here (if there is one)?

The crosshair symbol is used for a bunch of things:

- It's the Inspector's tab icon
- Used in Inspector>Rules for highlighting elements matched by a selector
- Used in Reps (Console, Debugger), and the old variable-view to select a DOM node in the Inspector

I think it's also used (or some variation of this concept) in React and Vue devtools, for their "Pick a component" features.

Given all that, I'm wondering if we should keep that icon for Reps, because it's somewhat (though not exactly) similar to what React and Vue devtools do, and investigate a different icon for the Rules feature.

Note: I also had a related issue where we use a blue highlight color on hover in Reps, but in Rules the blue highlight color means "enabled". One crosshair button is effectively a kind of "link" (it takes you somewhere else), and the other one is a toggle button.

**Comment by nchevobbe** [comment]
Yes, looks like it would be nice in the ux repo

**Comment by nchevobbe** [comment]
moved to https://github.com/firefox-devtools/ux/issues/108
