### ISSUE TITLE
[Expressions] 'let' statement in watch expressions behaves weird

### ISSUE THREAD

**Issue by Loirooriol** [firefox-devtools/debugger#6214]
1. Create a watch expression: `foo`. This variable doesn't exist, so you get

 - `foo`: (unavailable)

2. Add a watch expression: `let foo = 123`. Now `foo` is defined but previous expression is not reevaluated, which seems reasonable.

 - `foo`: (unavailable)
 - `let foo = 123`: undefined

3. Add a watch expression: `foo;`. Strangely this does not output `123`, I guess it's evaluated in another scope.

 - `foo`: (unavailable)
 - `let foo = 123`: undefined
 - `foo;`: (unavailable)

4. Click the refresh button. The `let` declaration does not throw so the code is evaluated in a scope different than in step 2. The last expression can read the variable so now all expressions are evaluated in the same scope.

 - `foo`: (unavailable)
 - `let foo = 123`: undefined
 - `foo;`: 123

5. Click the refresh button again. Now the expressions are evaluated in the same scope as in the previous step. This does not seem consistent.

 - `foo`: 123
 - `let foo = 123`: SyntaxError
 - `foo;`: 123

I would expect one of these:

 - Getting `123` at step 3 and getting the same output as step 5 at step 4. This seems what Chrome does.
 - Getting `123` at step 3 and getting the same output as step 4 at step 5.
 - Getting the same output as step 4 at step 5.

**Comment by jasonLaster** [comment]
@jimblandy @jorendorff what do you think we should do?

**Comment by jasonLaster** [comment]
Lets re-open this bug in bugzilla as it is server/platform side.

**Comment by jorendorff** [comment]
@jasonLaster Here are some options:

1. Use Babel to compile watch-expressions. Then we can inspect the AST, see if it's a let expression, and special case them or otherwise do whatever we want. (Plus, Babel syntax in watch-expressions.)
2. Wrap watch-expressions in `()` before running them. This forces them to be actual *expressions*; a `let` statement would be a SyntaxError.
3. Wrap watch-expressions in `{}` before running them. Expressions would still work. A `let` statement would be allowed, but the variable would be local to that watch-expression.

If we choose option 3, we get:
* `foo`: (unavailable)
* `let foo = 123`: undefined
* `foo`: (unavailable)
at steps 3, 4, and 5.

**Comment by janodvarko** [comment]
Work on this is covered by:
 [Bug 1580891](https://bugzilla.mozilla.org/show_bug.cgi?id=1580891) - Console expressions should allow let/const variables and classes

Honza
