### ISSUE TITLE
[Stepping]"step-over" (F10) takes a lot of time

### ISSUE THREAD

**Issue by evgi99** [firefox-devtools/debugger#6313]
I found out that "step-over" the code take time. i try to drill down and look for the reason for this performance reason and saw that probably it because code-mirror take time change page view (e.g. `updateHeightsInViewport` takes 14ms and is called both in `clearHighlightLine` and in `setHighlightLine`)

* attached file from https://perf-html.io that help me in my research - I recorded 2 step-overs

[Firefox 2018-05-15 19.52 profile.sps.json.gz](https://github.com/devtools-html/debugger.html/files/2006142/Firefox.2018-05-15.19.52.profile.sps.json.gz)

#goodnessSquad

**Comment by jasonLaster** [comment]
oh thanks!

**Comment by janodvarko** [comment]
A lot has been fixed since this bug report and performance should be much better.

I am closing the report, but if you still experience the bug please file a new report.

We are moving our bug tracking into Bugzilla, so please report further bugs here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Thanks,
Honza
