### ISSUE TITLE
Visually distinguish the skip-all-pausing state better

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6673]
Follow up from #6512, triggered be my just having a case myself where I wondered why breakpoints stopped working. The icon (which very light blue lines) on the skip button are the only visual `enabled` state right now.

Disabling the Breakpoint panel, both for exception checkboxes and breakpoint list, might just be enough, but maybe @violasong has more ideas.

For inspiration:

While Chrome's button is a bit stronger (changes style to not being crossed out), Chrome also visually mutes both the breakpoint indicators and the panel:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/8599/43025718-b5fc6f18-8c27-11e8-878b-3ad10214c659.png">

**Comment by violasong** [comment]
Ah, I had muted-looking breakpoint check boxes in the mockup, which could help, but sounds good to add more indicators https://mozilla.invisionapp.com/share/P4IA9FCQNGW

Muted breakpoint icons seem like a great idea. We could also create a bolder-looking version of the Skip All Pausing icon. Maybe this situation is important enough that the Skip All Pausing icon could expand to be larger with a text label when toggled on.

**Comment by fvsch** [comment]
Since I'll be working on Debugger icons shortly (in https://github.com/devtools-html/ux/issues/49), I would like some guidance about the icon itself.

Two options:
1. Keep the current behavior and design, just photonize the icon's shapes. This means that when we activate that button, the icon's color changes to blue.
2. Use a two-state icon. This means that when we activate that button's, the icon itself changes.

We have a few two-state icons in DevTools but they're rather subtle: the RDM icon and the "Pick a frame" icon both have a partial opacity fill that is added to parts of the icon when "active".

We've also discussed using a two-state icon for the "Item visibility" icon used by the Style Editor, which happens to be the same "eye" icon that Debugger uses for blackboxing (maybe we should change that one).

Also I'm a bit uncertain about the UX of two-state icons with "on" and "off" meanings (e;g. "normal" and "crossed out" designs), because I'm always unsure if the current design represents the current state ("breakpoints are currently disabled") OR if it represents the next state ("click me to disable breakpoints"). :/

**Comment by jasonLaster** [comment]
Adding @violasong's mockups

<img width="683" alt="screen shot 2019-02-09 at 4 45 44 pm" src="https://user-images.githubusercontent.com/254562/52528107-45394180-2c8a-11e9-910d-f5aede4e4dd4.png">

**Comment by jasonLaster** [comment]
@fvsch I think photonizing the icon is a great start. 

I like @violasong's idea of muting the checkboxes. I think that communicates that the breakpoints are globally disabled.

In terms of 2-state buttons, i'd need to see some mockups to wrap my head around the different options.

**Comment by fvsch** [comment]
> I like @violasong's idea of muting the checkboxes.

Same, but I wonder if using `<input type="checkbox" disabled>` would not work better?
Each platform has a "disabled" variant for checkboxes that users may already be familiar with, and which often looks muted.

So maybe something like:
- "disabled" variant for checkboxes
- grayscale filter for syntax-colored text (or just a single shade of gray)
- medium gray (or partial opacity) for other text

Small note on Chrome's "Debugger paused" message: if we ever want to add a message like they do, we probably should use a different wording. Since the main feature of the Debugger is to pause JS execution on breakpoints, I believe "Debugger paused" would be understood as "JS execution is currently paused on a breakpoint", and not as "Debugger's ability to pause JS execution is currently disabled".

**Comment by jasonLaster** [comment]
@fvsch I agree on all points

**Comment by digitarald** [comment]
Continued in https://bugzilla.mozilla.org/show_bug.cgi?id=1537884 . Lowest hanging fruit is just fading out the whole list and using disabled state for the gutter indicators. We can tweak the details of checkboxes and font colors later.

Might be a good first bug?

**Comment by digitarald** [comment]
@darkwing should I close this one in favor of the bug or keep it here as GFB?

**Comment by jnachtigall** [comment]
fwiw, I just spent some considerable time finding out why the debugger would not stop at all and also not even on a "debugger;" statement in Nightly while a clear profile and stable/dev edition as well as chrome worked. Via "about:config" I found that `devtools.debugger.skip-pausing` was set (I was away from firefox debugger for some month and must have set this back then, lol). 

Long story short the improvements in https://bugzilla.mozilla.org/show_bug.cgi?id=1537884 are nice, but it is just the gutter/list *not* the icon itself:

The icon button should really be a filled blue button. At the moment it is just a blue outline, not very visible imho:
![image](https://user-images.githubusercontent.com/3307404/64867932-aa00b400-d63e-11e9-939c-9768a3eb2ed8.png)

cc @fvsch in case this is already in the works somewhere.

**Comment by fvsch** [comment]
We could make the icon's "pressed" state more prominent, but I'm not super fond of that solution. The way I see it, users are going to focus on the "content" (the `debugger` statement in code, the breakpoints in the gutter and the sidebar), and may miss that the button is in "pressed" state even if we change its style.

I think we should do two things:

1. Add a style or annotation that shows that the `debugger` statement is inactive. Maybe the `debugger` text should be crossed-out, and we could have a tooltip explaining why on hover?
2. Explore more visible styles for the pressed state of the "Deactivate breakpoints", but I wouldn't make it super obnoxious.

**Comment by violasong** [comment]
What about showing a message banner at the top of the right sidebar, similar to the paused message, but it would say "Breakpoints deactivated"? Maybe with light gray instead of yellow styling to show that it's more of an inactive state.

**Comment by digitarald** [comment]
The screenshot seems like it suffers again from the dark mode's low contrast issue. I am not sure if a gray warning bar gets the right attention. Showing a warning via #60 might also point at it, within a more visible context.

Related, maybe remembering skip-pausing beyond the devtools session doesn't seem helpful. Given the footgun potential, are there use cases that I am missing?

**Comment by fvsch** [comment]
> Given the footgun potential, are there use cases that I am missing?

I think there's one with hostile scripts that spam `debugger` statements to make using DevTools impossible. Some anti-adblock scripts, cryptominers, script obfuscators etc. do that.

So the use case would be "work around hostile scripts that try to block devtools, and remember this even if I close and reopen devtools". If we remove the "and remember this" part, we still serve this use case well enough IMO.

**Comment by digitarald** [comment]
> I think there's one with hostile scripts that spam debugger statements to make using DevTools impossible. Some anti-adblock scripts, cryptominers, script obfuscators etc. do that.

Right. The impact of not remembering would be that the user will hit one `debugger` statement, but after disabling pausing will be able to continue debugging. Doesn't seem too hostile, and it could be remembered for the same Firefox session.

**Comment by jnachtigall** [comment]
So there seems to be several issues here:
1. Skip breakpoints button **not being visible enough**, e.g. not enough contrast, imho also not enough "fill". I think Chrome's button is more visible because it is filled but maybe more contrast would be good enough:

![image](https://user-images.githubusercontent.com/3307404/65041896-096d0580-d958-11e9-9be3-ac562fc14d01.png)
(Left Chrome, right Firefox)

2. 
> showing a **message banner** at the top of the right sidebar, similar to the paused message, but it would say "Breakpoints deactivated"? Maybe with light gray instead of yellow styling to show that it's more of an inactive state.

This sounds great to me though actually a button state and its actively pressed icon alone might convey this meaning.

3. 
> Add a style or annotation that shows that the **debugger statement** is inactive. Maybe the debugger text should be crossed-out, and we could have a tooltip explaining why on hover?

Well, I started with normal breakpoints first (which should have been "grayed out"), then when these not work resorted to simpler "debugger;" statement (no source maps). So I do not think this would have helped me and it sounds a bit complicated (too much effort just for "debugger" statements)

4. "**Not remembering** skip-pausing beyond the devtools session" sounds great too and should probably put into its own dedicated issue.

So for me 1 (and 2) and 4 sound great whereas 3 sounds like too high effort for little outcome.

**Comment by fvsch** [comment]
> I started with normal breakpoints first (which should have been "grayed out")

We don't turn them gray but there still is a "deactivated" style applied, see normal vs deactivated on the right:

![deactivated-breakpoints](https://user-images.githubusercontent.com/243601/65044063-813d2f00-d95c-11e9-8884-b5300b5aff94.png)

The main reason for not using gray here is that we have different colors for different types of breakpoints (blue for breakpoints, purple for log points, and orange for conditional breakpoints), and this style keeps that information.

**Comment by digitarald** [comment]
Related, I really like Safari's warning bar that I recently discovered – especially that it has the `enable` button so it provides both warning and solution: 
<img width="307" alt="image" src="https://user-images.githubusercontent.com/8599/69214251-3c2fa780-0b1b-11ea-8d4e-4022cd7f1dba.png">

UI-wise, we could re-use the "paused reason" element that we already have, in the same position.

**Comment by violasong** [comment]
I like Safari's!  We could even have a one-liner 

> (info icon) Breakpoints Disabled [Enable]

One other issue: the current translucent gray overlay styling looks a bit odd to me because of how intense it is, with some elements staying white or a lighter gray. If we implement the bold banner solution, I'd be interested in toning this down to something that is more like Chrome's effect. 

Next steps? Do we need a mockup?

**Comment by digitarald** [comment]
> Next steps? Do we need a mockup?

That'd be great. Would be good to have it revisited in conjunction with the paused indicator (which could also have a continue button baked in; or could be even taken out since we have the overlay now).

**Comment by digitarald** [comment]
> If we implement the bold banner solution, I'd be interested in toning this down to something that is more like Chrome's effect.

@violasong Could be good easier for community if we had a simple mockup, since we have a lot of contributors coming in atm .

**Comment by violasong** [comment]
Sorry for the long delay on this!

Here's a [mockup](https://www.figma.com/file/pVg7LMXy2dvHXkaMLTj0HJ/Breakpoints-deactivated?node-id=1%3A4).

<img width="982" alt="image" src="https://user-images.githubusercontent.com/55994/81025930-41648280-8e2d-11ea-82ac-d9fa676d18d0.png">



1. Change Paused on Breakpoint to have the icon on the left
2. Yellow "Breakpoints deactivated" banner
3. Alternate idea: Gray "Breakpoints deactivated" banner - subtler look, but goes with the "deactivation" idea

These banners might make it unnecessary to have a gray color over the entire breakpoints section. It would look nicer to go back to just disabled checkboxes.

cc @digitarald @fvsch

**Comment by fvsch** [comment]
I like it: looks clean, adds needed information, and the Enable button makes sense. No opinion on yellow versus gray.

> These banners might make it unnecessary to have a gray color over the entire breakpoints section. It would look nicer to go back to just disabled checkboxes.

Works for me. Me made this style because users would miss the "Deactivated" state (active footgun), but the banner could fix that. And as implemented the current overlay style has a few quirks that I'm not happy with, e.g. you can still interact with everything and add/remove breakpoints, Event Listener breakpoints, etc., and we special-case adding or enabling a classic breakpoint to force-enable breakpoints again BUT only do that for classic breakpoints.

How should interactions with the content work when breakpoints are deactivated?
- Block everything? (No CRUD operation on any pane.)
- Allow everything, and re-enable breakpoints on any change?
- Allow everything, and don't change the "Deactivate breakpoints" state when changing something in the panes?

**Comment by janodvarko** [comment]
Cloned into:
https://bugzilla.mozilla.org/show_bug.cgi?id=1695203

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
