### ISSUE TITLE
[Breakpoints] Break at wrong location

### ISSUE THREAD

**Issue by janodvarko** [firefox-devtools/debugger#6873]
STR:
1) Create a breakpoint in components/Tabs.js on line 48 `return dom.div(`. It should auto hit shortly.
2) Press Resume button (or F8)
3) The debugger halts on line 53 within a loop, so further resume breaks there again -> BUG

The breakpoint is not set in the loop. There is no reason it should break there.

Honza

![image](https://user-images.githubusercontent.com/37785/44529310-0e776b00-a6ec-11e8-9c5e-eb075b3f488d.png)

**Comment by loganfsmyth** [comment]
This is because of this logic: https://searchfox.org/mozilla-central/rev/fcfb479e6ff63aea017d063faa17877ff750b4e5/devtools/server/actors/source.js#949. In the generated code, original line 48 -> 53 are all on the same line, and once the location propagates to the server, all it has is the generated line number, so it ends up creating breakpoints inside of the `.map` callback too.

The fix most consistent with the current approach might be to pass a start/end column range (or even a sequence of multiple column ranges), rather than leaving the column information `undefined`.

**Comment by digitarald** [comment]
@loganfsmyth I'd assume that this would be fixed by column breakpoints? Should we dupe it?

**Comment by jasonLaster** [comment]
@digitarald i think so, but lets keep it open and revisit in a couple of weeks.
