### ISSUE TITLE
Confusing tooltips on step buttons

### ISSUE THREAD

**Issue by kenjiO** [firefox-devtools/debugger#6993]
It's hard for me to understand the tooltips showing the keyboard shortcuts for the step buttons.  I think it would be better to use parenthesses and add an 'or' between the two shortcuts. ie: `(⌘\ or F8)`

The tooltips for the toolbox panels use `cmd` instead of `⌘` and also use '+' for multikey shortcuts.  Do you want to do this here as well?

![](http://g.recordit.co/R7OyZBMhzw.gif)

**Comment by twhite96** [comment]
I got this one. /claim

**Comment by twhite96** [comment]
I think putting parens around multi-key options is a great idea. It is always a bit confusing when an app or some part of a UI doesn't distinguish how to accomplish keyboard shortcuts. This improves usability. Going to work on this tomorrow.

**Comment by twhite96** [comment]
Looks like this is fixed. Seems the desired behavior is working in Firefox Developer Build.

![](https://cl.ly/a0ca2732c00f/Screen%252520Recording%2525202018-09-23%252520at%25252011.33%252520PM.gif)

@jasonLaster maybe this is fixed? I don't want to unclaim this if there is something I can do.

**Comment by nchevobbe** [comment]
Hello @twhite96 , so here the issue is on the stepping / pausing buttons: 

<img width="159" alt="image" src="https://user-images.githubusercontent.com/578107/45938270-b96b9500-bfc8-11e8-9041-5d163d3f526d.png">

There are 3 things that differs from tooltip in other places (like on the panel tabs) :

<img width="383" alt="image" src="https://user-images.githubusercontent.com/578107/45938249-64c81a00-bfc8-11e8-9bd1-fac496757c88.png">

1. We use the `⌘` char in the debugger, where we use `Cmd` in other places
2. We user the `\` char to separate multitple shortcuts, where we could use a more explicit `or`
3. We don't show a `+` between chars when the shortcut is multi-keys.

I think using `⌘` is fine, we do it in several places in the debugger. But we should drop `\` in favor of `or`, and use the `+` when needed.

By the way, looking at the "help" modal, we already use the `+`. 

<img width="873" alt="image" src="https://user-images.githubusercontent.com/578107/45938265-99d46c80-bfc8-11e8-8ea9-ee8de310d3fc.png">

---

It looks like we don't reference all the possible shortcut, it may be nice to do it there as well

**Comment by twhite96** [comment]
Okay. Misunderstood the issue. I was trying to find the component/css file where the tooltips are but couldn't. I'll have to read through the codebase a couple times to see where things are.

**Comment by nchevobbe** [comment]
So the stepping buttons are created here https://github.com/devtools-html/debugger.html/blob/ffaf7049156cb17b3dfccfdbf02835661515619c/src/components/SecondaryPanes/CommandBar.js#L140-L162

and the Pause one https://github.com/devtools-html/debugger.html/blob/ffaf7049156cb17b3dfccfdbf02835661515619c/src/components/SecondaryPanes/CommandBar.js#L169-L203

You can see that they all use the `debugButton` function, that we import https://github.com/devtools-html/debugger.html/blob/ffaf7049156cb17b3dfccfdbf02835661515619c/src/components/SecondaryPanes/CommandBar.js#L22

https://github.com/devtools-html/debugger.html/blob/ffaf7049156cb17b3dfccfdbf02835661515619c/src/components/shared/Button/CommandBarButton.js#L17-L37

So, now for the tooltip, let's have a look for the pause button.

https://github.com/devtools-html/debugger.html/blob/e6113cf4d9e972fc681939de859a6a748a28bb69/src/components/SecondaryPanes/CommandBar.js#L202


The string comes from https://github.com/devtools-html/debugger.html/blob/a3085aec5bd0b4da1661f81707b921fd12801a97/assets/panel/debugger.properties#L63

The `%S` part means there's a string substitution being made, with the result of `formatKey("resume")`.

https://github.com/devtools-html/debugger.html/blob/e6113cf4d9e972fc681939de859a6a748a28bb69/src/components/SecondaryPanes/CommandBar.js#L64-L73

It uses then https://github.com/devtools-html/debugger.html/blob/181074bee99b0e9e6042792ea6123d6588e36a2b/src/utils/text.js#L29-L40

---

I hope this will help you getting started :)

**Comment by twhite96** [comment]
Yep! Thanks @nchevobbe.

**Comment by jasonLaster** [comment]
How's it going @twhite96?

**Comment by jasonLaster** [comment]
@twhite96 that's okay. ping me if you have questions

**Comment by twhite96** [comment]
Working on this now. Just need to update my fork.

**Comment by darkwing** [comment]
Great!  Welcome back @twhite96 !

**Comment by twhite96** [comment]
Looking over the lines that @nchevobbe pointed out and I am starting to get what is happening. I'm going to take a few notes and come back to it later tonight.

**Comment by darkwing** [comment]
Hello @twhite96!  How is this going?  Anything I can do to help?
