### ISSUE TITLE
[QuickOpenModal] Bold font of highlighted <mark>'s are blurry on Windows

### ISSUE THREAD

**Issue by gerdneuman** [firefox-devtools/debugger#7490]
Similar as https://github.com/devtools-html/debugger.html/issues/5584#issuecomment-389837621

On Windows the bold font when `Ctrl+P` are "blurry", just look at the letter `a` in bold `react` (you might need to middle-click on the images to have them open full width on a new tab):

![image](https://user-images.githubusercontent.com/12525563/49863559-d2822600-fe00-11e8-8547-df7321f4b01a.png)

Compare to Linux where it is crystal clear:
![image](https://user-images.githubusercontent.com/12525563/49863580-e62d8c80-fe00-11e8-8974-781856af2683.png)

I guess the used font on Windows is just not particular suited for `bold`? But I am not a fonts expert.

Pinging @fvsch who already helped fixing https://bugzilla.mozilla.org/show_bug.cgi?id=1457086#c9 with great analysis.

FWIW, here are too screenshots of VSCode and Chrome Debugger, also both on Windows, and both look fine:

![image](https://user-images.githubusercontent.com/12525563/49864122-0dd12480-fe02-11e8-9c19-8ae538e12500.png)

![image](https://user-images.githubusercontent.com/12525563/49864103-001b9f00-fe02-11e8-927c-74469097237a.png)

**Comment by fvsch** [comment]
First thing that comes to mind is that box-shadow should probably be black in the dark theme, and not some shade of medium gray.

But on the current topic: I'm not sure we can do much better without bumping the font-size. And we're already at 12px, which is our "big" font size, used for tabs and panel headers, so I'm reluctant to go for a bigger font-size. Not sure if Chrome is getting better results here because they're using 13px or if they're using a different font.

It would be interesting to check what font is effectively used here on Windows. Can someone check using the Browser Toolbox ("Fonts" tab in the Inspector)?

One possible solution would be to avoid bold altogether. It doesn't work for fuzzy matches anyway, when we make every other letter bold. (See the "replaceWith" example.) We're discussing search highlights in https://github.com/devtools-html/ux/issues/14, maybe we should use the same style here?

Quick test:

![screenshot](https://user-images.githubusercontent.com/243601/49879109-89929780-fe29-11e8-8287-87ec5019a12f.png)

**Comment by gerdneuman** [comment]
> Can someone check using the Browser Toolbox ("Fonts" tab in the Inspector)?
Here's what the fonts tab says (Windows 10):

![image](https://user-images.githubusercontent.com/12525563/49927247-c27c4c00-febd-11e8-854a-df0b21a98089.png)

> One possible solution would be to avoid bold altogether. 

Yeah, though personally I find changing the background color a bit "too much". VSCode and Chrome (also) seem to use brigther font colors. Highlighted is blue (VSCode) or white whereas the unhighlighted text is a bit more greyish.

**Comment by darkwing** [comment]
@mcroud @violasong Any ideas to add to @fvsch 's?

**Comment by violasong** [comment]
Ah that's unfortunate - aren't we using the system sans-serif font for this kind of text? I'm a fan of the bold white look and am hoping we can keep that but fix the bold.

**Comment by fvsch** [comment]
I personally dislike the bold style because it just doesn't work for fuzzy matching (where we highlight several isolated characters in a string, rather than a continuous fragment of that string).
Looks like VS Code handles that by using bold + color.

Not sure what is happening re. the bold font, but that kind of imprecision is bound to happen for bold + small size (12px) + 1x rendering + some combinations of fonts and operating systems.

It looks like the difference between Windows and Linux in @gerdneuman's screenshots is that their Windows setup uses very strong subpixel (color) antialiasing:

![windows-subpixel](https://user-images.githubusercontent.com/243601/52603302-90a84700-2e66-11e9-88d6-8eb2c23c706b.png)

While the Linux screenshot shows grayscale antialiasing, and some subtler subpixel antialiasing for some of the text.

Subpixel antialiasing tends to make text look "fatter", since it adds light to the neighboring pixels to create an effect of higher resolution.

One solution might be to try to use `font-weight: 600` on Windows instead of `font-weight: 700`, if the font we use on Windows supports this weight. Then we'll get a semi-bold font.

**Comment by mcroud** [comment]
Which ever method we pick, I'm guessing we can perhaps just target standard res screens on Windows? Perhaps bumping up the font size in just this scenario? I know it creates another stress case but an extra px upsize might solve the issue without having to alter the highlight method.

I think @fvsch suggestion of looking at semi-bold weights is a good start. If the change in font weight substantially reduces the contrast with the normal text, maybe we could use in addition to text highlighting?

Just voicing another suggestion, I known we don't use this pattern anywhere else so likely not a contender, but using an underline would remove any interferance with the letterforms themself. Again, perhaps only targeting the standard res/windows scenario.

**Comment by darkwing** [comment]
@derek-li Would you be able to try this out?  You're on Windows, correct?

**Comment by darkwing** [comment]
I just tested locally on a Windows PC and the font does look a bit yucky.

`font-weight: bold` (current):

![font-bold](https://user-images.githubusercontent.com/46655/55969732-ecfbcd00-5c43-11e9-8979-94e9e203ef89.png)

`font-weight: 600` (@fvsch's suggestion)

![font-600](https://user-images.githubusercontent.com/46655/55969781-fedd7000-5c43-11e9-9684-1fcb4241723a.PNG)

Here's what bold looks like in the Net Monitor:

![font-netmonitor](https://user-images.githubusercontent.com/46655/55969821-0ef54f80-5c44-11e9-9b6b-5c583e94c0c5.png)

The bolding looks yucky but it's at least consistent.  I'm closing for now but please open if you have more ideas for improvement!
