### ISSUE TITLE
Consolidate Icon CSS Files

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7735]
At the moment we have three files which contain CSS for icon display:

- src/components/shared/SourceIcon.css
- src/components/shared/Svg.css
- src/components/PrimaryPanes/Sources.css

There's unnecessary overlap in some of their styles which we should resolve.  Ideally we have one CSS file with all of the base icon stuff.

**Comment by darkwing** [comment]
@notjaril You may enjoy this one 👍

**Comment by jasonLaster** [comment]
I'm re-opening because I could not land the Accordion.css changes in MC

This commit shows the portion that i had to revert in debugger.css and Accordion.css. 
https://hg.mozilla.org/mozilla-central/rev/1c7af47c1ba4

The reason for the revert was that this test (browser_dbg-expressions-focus.js) was failing with it.
The best path forwards is to try to re-land the debugger.css changes in MC.

**Comment by darkwing** [comment]
@fvsch ^^

**Comment by fvsch** [comment]
(Side note: we should probably update assignee (me) and labels.)

Just to be clear, commit 3d9f98d7ff8d02c433e1c7e726dd34e44b12b20e shows what was reverted too?

**Comment by fvsch** [comment]
I swear if the issue is that I changed the accordion headers from 24px to 25px height and some `clickAtPreciseCoordinatesBecauseWhatCouldGoWrongAmarite(0,24)` code is failing, I'm going to shout at some clouds.
