### ISSUE TITLE
Debugger does not pause at breakpoint

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#7804]
This is reproducible with the latest Github sources: 

**Steps to reproduce**
1. Open https://nchevobbe.github.io/demo/console-test-app.html
1. Open the debugger
1. Open the `webpack:///framework/src/App.js` file
1. Put a breakpoint at the first line of the render method (should be line 11, on the `const`):  
```js
  render() {
    const {
      dispatchLog,
      log
    } = this.props;

    if (log === "trace") {
```
5. Put another breakpoint on the `if` line
5. In the test page, scroll down to the `React/Redux` section, and hit the `trace` button

**Expected results**

The debugger pauses at the first breakpoint.

**Actual results**

It only pauses on the second one.

---

I think that putting the first breakpoint should make it slide? Not sure about that though.

**Comment by jasonLaster** [comment]
Yep. Let's wait until specificity lands

**Comment by loganfsmyth** [comment]
Looks like this still happens with specificity at the moment, because empty-lines is still powered by pause points, and it's actually the `} = this.props;` line where you'll pause, not the `const {` line, so the wrong line is marked as empty.

@jasonLaster Looks like we'll want to look into changing that to use the `getExecutableLines` API, like we talked about the other day.

**Comment by loganfsmyth** [comment]
This works now.
