### ISSUE TITLE
[scopes] Make map scopes opt-in

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7806]
The feature Map Scopes currently has a significant performance cost for the parser worker and non-trivial cost for the main thread.

w/ map scopes on -- http://bit.ly/2Tf9KqC
w/ map scopes off -- http://bit.ly/2Tg4aUL

The reason for that is that parsing the generated file is often slow, building scopes list can be slow, and building generated lists is about ~60ms on the main thread for debugger.html

We can make map scopes opt-in and let users choose to have the feature. This could be good for several reasons:

1. users will know that the feature exists :)
2. users will know that we want feedback, more likely to send us reports if mapping fails or is slow
3. users can keep it off if they want speed

**Comment by digitarald** [comment]
Thanks for investigating and sharing the profiles of the patch.

The difference between the profiles is harder to determine; I am unsure where the main thread time is being spend as the heaviest callers are still present.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/8599/51783756-7f83da00-20f3-11e9-9127-bfd442d51a42.png">

Do we know where exactly the scope mapping adds time (I assume on pause and every step) and what impacts the cost (large code base, many variables?)

**Comment by loganfsmyth** [comment]
@digitarald Does that include work done in a worker? The main things for scope mapping are: 
* Parse the full generated file in the parser worker
* Looking up all the mappings in the sourcemap worker

Since both of those happen in a worker, we do have to wait a while for it to finish, but it's not visible as work done in the main thread. We do some work on the main thread after that, but it's probably not where we spend most of our time.

**Comment by digitarald** [comment]
I was investigating based on the initial statement from the issue description (*non-trivial cost for the main thread*), but I understand now that most of it is on the worker.

Worker-wise there is definitely overhead of 3+sec per step:

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/8599/52242146-944a3580-288a-11e9-8505-e520361bf6e8.png">

Before preffing this off, did we consider exposing this as option in the Scopes panel? I assume this would land as option in DevTools preferences?

Since this is already OTM, another mitigation would be to be smarter how we update the scopes; so it doesn't add visual noise which is more a perceived performance challenge. If we just make switching out the scopes visually stable, this might work.

**Comment by loganfsmyth** [comment]
I think if we pref it off, almost no-one will use it. I'd definitely prefer exploring UI options that allow users to opt in to scope mapping. It seems like the nicest way would be a checkbox to enable variable mapping in the scope pane or something. An option in the devtools settings would work too, but it's still dramatically less discoverable that way.

**Comment by jasonLaster** [comment]
I'm proposing adding a setting in the scopes panel that is discoverable.

With that said, we should have a better tree idea of the performance cost.
I'll share some numbers when I'm at my computer.

Harald, the 3 secs was likely the first pause bc that's when we build the
full scope tree for the two files.

Logan, one of my concerns is the 3 seconds blocks other parser worker
tasks.

I think we could move the scopes work to it's own worker. We could also
shard by source or move other things like mapping expressions to its own
worker for performance.

**Comment by jasonLaster** [comment]
some initial requirements

1. should only appear if there are valid mappings (original, column based mappings)
2. should have a link to an mdn page where others can learn more
3. should be easy to turn off if they don't like it

**Comment by janodvarko** [comment]
Cloned in to Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1695621

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
