### ISSUE TITLE
[Breakpoints] Add Log Points

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7816]
It should be possible to add a log and condition to a breakpoint

- [x] console log showing in breakpoints panel for log points #7672 
- [ ] Fold Conditional & Log into unified Edit Breakpoint form #7816

Server work: [Bug 1526554](https://bugzilla.mozilla.org/show_bug.cgi?id=1526554)

**Comment by bhackett1024** [comment]
I think it would be nice if there was a simple way to toggle which logpoint messages are shown in the console.  This would be a nice feature (who hasn't been overwhelmed by logging output when debugging something?) and provides extra functionality that just using console.log() doesn't provide.  The console filtering UI could be used, but this doesn't seem quite sufficient.

The simple way to do this is to remove messages from the console when a logpoint is disabled, and put them back in the console when the logpoint is reenabled.  I'm not sure about the right interface in other cases, though.  Should removing a logpoint or changing its text or condition remove the old messages as well?  (The answer is simple when using web replay: yes we should, since we can regenerate the older messages according to the currently installed logpoints.)

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
