### ISSUE TITLE
Breakpoint colors are hard to distinguish

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#7933]
Using the light theme, a few issues with breakpoint indicators' styles:

1. Both conditional breakpoints and Log points are orange. Could we use different colors?
2. When those breakpoints are disabled, they become translucent blue. We should probably use a partial-opacity version of the original color.

There are more UX issues, which might be listed elsewhere, like:

- Clicking on a conditional breakpoint or a log point removes it, while I expected to go back to the editing mode to tweak or fix that breakpoint. (Edit: some UX work under way for an editing overlay.)
- There is no accessible text information. Maybe we should use `title` attributes (not perfect but a start), so that we can show the value of the condition or log point on hover? (`Conditional breakpoint: <condition value>`)

**Comment by jasonLaster** [comment]
> Both conditional breakpoints and Log points are orange. Could we use different colors?

we are switching logs to purple 70/60

* Clicking on a conditional breakpoint or a log point removes it, while I expected to go back to the editing mode to tweak or fix that breakpoint. (Edit: some UX work under way for an editing overlay.)

> that's tough... i also want it to be easy to add/remove. i think shift+click will be "toggle disabled", is it madness for alt+click to be edit breakpoint"? i think the panel will have the ability to view/edit both condition and log in the future

* There is no accessible text information. Maybe we should use `title` attributes (not perfect but a start), so that we can show the value of the condition or log point on hover? (`Conditional breakpoint: <condition value>`)

**Comment by fvsch** [comment]
Looks like this is done:

1. Different colors: check
2. Title on conditional breakpoints and log points: check (on the column marker)
