### ISSUE TITLE
Debugger does not pause at breakpoint

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#7970]
**Steps to reproduce**
1. Go to https://nchevobbe.github.io/demo/console-test-app.html
1. Click on the `trace` button in the React/Redux section, at the bottom
1. Open the console
1. There should be a `console.trace()` log in `App.js:17`
1. Click on the message location to jump to the debugger
1. Add a breakpoint on line 17
1. In the page, click on the `trace` button again

**Expected results**

The debugger should pause on line 17

**Actual results**

The debugger does not pause

---

This is with latest mozilla-central build

**Comment by loganfsmyth** [comment]
Things are in a bit of an intermediate state right now because of our breakpoint changes. The breakpoint-able line is now line 20, but that shows up as disabled for the time being because we have to tweak a few things.

Do you know which logic decides that line 17 is the line to to reference in App.js?

**Comment by darkwing** [comment]
I had a hard time reproduce this;  I did my best and ended up paused at line 6 (`if (e.target.tagName === "BUTTON") {`)

Tested in Nightly.
