### ISSUE TITLE
[Tabs] more tabs dropdown is clipped by the secondary sidebar

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7985]
STR:

1. add a bunch of tabs
2. click the more tabs dropdown

My hunch is that this regressed when we did the recent RTL css.

<img width="339" alt="screen shot 2019-02-18 at 2 56 54 pm" src="https://user-images.githubusercontent.com/254562/52975982-a3a2a600-3395-11e9-80a0-2f3e495ca41e.png">

**Comment by jasonLaster** [comment]
CC @fvsch @darkwing

**Comment by fvsch** [comment]
If it regressed it was at a different point because #7948 is not merged yet.

**Comment by fvsch** [comment]
@jasonLaster I regressed it here:
https://github.com/firefox-devtools/debugger.html/pull/7890/files#diff-b986140cf2f6dfb8d446b61cf60d4b1bR12

I used `offset-inline-end` (old syntax, used to be supported in Firefox) instead of `inset-inline-end` (new syntax, supported in Firefox and Chrome).

The good news is that #7948 fixes it.

**Comment by fvsch** [comment]
Should be fixed on `master`.

**Comment by nagpalm7** [comment]
I think this issue is fixed, it can be closed.
