### ISSUE TITLE
[Search] Results clip the modifiers

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#8003]
It looks like the search results clip the modifiers so they do not show. I wonder if we can use flexbox here so that we guarantee that modifiers always appear.

---

<img width="446" alt="screen shot 2019-02-20 at 12 41 33 pm" src="https://user-images.githubusercontent.com/254562/53112399-1a15e400-350d-11e9-9e3c-b53897b0253d.png">

---
<img width="399" alt="screen shot 2019-02-20 at 12 41 28 pm" src="https://user-images.githubusercontent.com/254562/53112400-1a15e400-350d-11e9-9400-21db8d7f06d0.png">

**Comment by th7nder** [comment]
I experimented with it a bit and turns out that just changing width of the input box does the job, because inputs have a built-in width. Currently it stops the input from shrinking, because it works as the flex-basis.
I wonder if it'll do ok, or shall we do something like 'modifiers button' with a dropdown from a certain size.
![2019-02-28 14 13 21](https://user-images.githubusercontent.com/8305170/53568862-5b3c7280-3b63-11e9-9c1a-3b73497940c1.gif)

**Comment by asishkr123** [comment]
Hi, i am new to this community and would like to contribute.  Can i work on this issue??

**Comment by jasonLaster** [comment]
@th7nder that sounds fine. I don't think we need to add a new dropdown.  At a certain size it is okay if the modifiers are not visible...

**Comment by jasonLaster** [comment]
@asishkr123 i'm not sure if @th7nder is on it or not

**Comment by th7nder** [comment]
I think I can finish it so I'll claim this issue.
