### ISSUE TITLE
[Workers] Use one tree instead of one tree per thread

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#8005]
We currently have one source tree per thread, this creates an issue for scrolling, focusing, and other keyboard navigation.

We should take advantage of the fact that the tree composes nicely and use one tree instead

**Comment by AnshulMalik** [comment]
Should we merge all sources into one tree or switch trees based on the selected thread?

If we are going to have separate trees, then what happens when we have tabs open from multiple thread sources and we say show in tree while the other thread is selected?

If we merge them, we might need to take care of duplicate scripts.

**Comment by jasonLaster** [comment]
we'll keep the same UX just have one tree component. Working on this now

**Comment by janodvarko** [comment]
@jasonLaster This, has been already done, correct?
I am closing this report, but let me know if there is something I should clone into bugzilla as separate bug.

Honza

**Comment by jasonLaster** [comment]
Yep
