### ISSUE TITLE
Offset-inline-* not supported in Chrome

### ISSUE THREAD

**Issue by jaril** [firefox-devtools/debugger#8017]
Noticed that the close buttons for Watch Expressions and XHR Breakpoints weren't displayed correctly on Chrome. I think this is related to the switch from `offset-inline` => `inset-inline` (#7948), where `inset-inline` is [only supported by Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline-end) for now.

@fvsch is there a way to still make `inset-inline` properties work for Chrome, where we wouldn't run into specificity problems(#7941)?

Firefox | Chrome
------------ | -------------
<img width="320" alt="screen shot 2019-02-22 at 10 32 48 am" src="https://user-images.githubusercontent.com/15959269/53252578-3e98ca00-368d-11e9-845c-b626b7c4748d.png"> | <img width="264" alt="screen shot 2019-02-22 at 10 14 15 am" src="https://user-images.githubusercontent.com/15959269/53251868-a5b57f00-368b-11e9-8875-057a9e64327e.png">

**Comment by darkwing** [comment]
Good spot @jaril.  We could duplicate properties but I don't think it's a priority.

**Comment by fvsch** [comment]
So it turns out that Chrome does support `inset-(inline|block)-(start|end)` since Chrome 69, but it's behind the `chrome://flags/#enable-experimental-web-platform-features` flag (unlike the margin/padding/border logical properties).

One solution would be to add `postcss-bidirection` back in, but the extra generated code for margin/padding/border etc. is overkill just for `inset-inline` support.

Searching through the CSS codebase I'm finding only 6 uses of `inset-inline-*`, and:
- half of them could be replaced with flexblox (we use absolute positioning to place a button at the end of a row), with better results for vertical alignment;
- and for the other half we can probably write the direction-dependent styles by hand, e.g.

```css
[dir="ltr"] .search-field .img.search {
  left: 6px;
}
[dir="rtl"] .search-field .img.search {
  right: 6px;
}
```

**Comment by jasonLaster** [comment]
i propose leaving a note in our local-development.md doc for RTL support that if you're using chrome setting the flag in `chrome://flags/#enable-experimental-web-platform-features`  could help. That's the primary use case
