### ISSUE TITLE
[CallStack] Vue icons don't display on frames

### ISSUE THREAD

**Issue by chujunlu** [firefox-devtools/debugger#8084]
I spotted this in both Chrome and Firefox.

STR:
1. Debug http://todomvc.com/examples/vue/
2. In debugger, open the app.js file in the editor pane.
<img width="334" alt="screen shot 2019-03-05 at 6 57 52 pm" src="https://user-images.githubusercontent.com/38041280/53845840-a0541080-3f78-11e9-859c-dfa25cb0f37b.png">

3. Set a breakpoint at line 74, within the `addTodo` method.
4. On Vue todomvc site, add a todo.

<img width="428" alt="screen shot 2019-03-05 at 6 05 08 pm" src="https://user-images.githubusercontent.com/38041280/53845753-523f0d00-3f78-11e9-8ac1-6be4e810f241.png">
 
I'm not sure if this bug is in any planned future polish.

**Comment by fvsch** [comment]
@chujunlu Good catch. It looks like the issue is that we have different logic to identify the framework name in different places, and use those two names:

- `Vue`
- `VueJS`

(For the record, the brand name is `Vue.js`.)

When we use those as class names, we end up with either `vuejs` or `vue`, and we only style one of those:

```css
.img.vue {
  background-image: url(/images/sources/vuejs.svg);
  background-color: transparent !important;
}
```

I'll make a CSS fix, but it would be great if we could harmonize this on the JS side.

**Comment by chujunlu** [comment]
Agree. I looked into the JS side - tried to see how the library name is generated and how other components successfully display Vue icon - but I haven't figure it out.
