### ISSUE TITLE
Primary panel is missing a bottom border

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#8127]
When you open the debugger without any tabs selected, and they primary panel is small enough, it misses the bottom border.

![](http://g.recordit.co/tZtEvqggiw.gif)

**Comment by fvsch** [comment]
Should we be able to make the primary panel (Left sidebar + main content) that small, to begin with?
A minimum height of at least 100 or 150px might make sense.

**Comment by yogmel** [comment]
Hi everyone,

Can I work on this issue? 

Thanks!

**Comment by darkwing** [comment]
SureaYep!  Go for it! :)

**Comment by yogmel** [comment]
Thanks! I will work on it shortly and will give you updates :)

**Comment by ruturajv** [comment]
While your at it, perhaps addition of `cursor: nw-resize` might also help.. @jasonLaster ?

**Comment by fvsch** [comment]
I'm already seeing a `nw-resize` cursor here (on Linux).

One thing I'm noticing is that in Inspector in vertical mode, the horizontal separator has a different style: it's 2px high and has a color change on hover. Perhaps we should use this same style in Debugger for this horizontal separator?

**Comment by yogmel** [comment]
Hi all,
Sorry for the late reply.

@ruturajv, I understand why you mentioned the `cursor: nw-resize`, it is hard to target the splitter on the right panel.
I inserted a `z-index` to it, so it solved both the border problem and the difficult targeting.

![border-bottom](https://user-images.githubusercontent.com/3901809/54778677-1e105100-4bf4-11e9-86bd-ef58c82364a2.gif)

Regarding the height of the panels, I can insert a `max-height` or a `min-height`, depending on which panel it going to be selected.

- If we select the **bottom one** (with the Breakpoints and Watch Expressions), we would need to change a React file, because there is a `maxSize` variable determining its max-height in `App.js:162`.
- If we select the **top one** (Sources, Outline and Welcomebox), we can insert a CSS style on `SplitBox.css`. Then, I would just need instructions on how to select it. Currently there is a `.split-box > .uncontrolled` selector, but probably we could use a more specific setting, such as `.horz .split-box > .uncontrolled`.

Also, we could use @fvsch suggestion and make it similiar to Inspector Splitter. I think that's a good idea.

Let me know what you think!

**Comment by fvsch** [comment]
- Good find re. the z-index issue!
- The 2px horizontal splitter looks great IMO. Could we also use the color change on `:hover` like the Inspector does?

For the min-height part, I looked at how the split-box component handles it and it's somewhat complex (we can have nested split-boxes). There is room for improvement there, but we should probably discuss it in a different issue.

I suggest we limit this bug to the z-index issue and perhaps the 2px style for the horizontal separator.

Can we check that all separators are always rendered above the content panes, in both vertical and horizontal mode? This is what I'm getting by setting this style:

```css
.splitter {
  background: red !important;
  border-color: red !important;
}
```

![horizontal mode screenshot](https://user-images.githubusercontent.com/243601/54782421-2fbb1e00-4c1f-11e9-9d85-ca7cd2ee1ce3.png)

![vertical mode screenshot](https://user-images.githubusercontent.com/243601/54782425-3053b480-4c1f-11e9-8086-e6d1610e01cd.png)

Definitely some z-index issues going on.

**Comment by yogmel** [comment]
Hi everyone,

I have experienced with @fvsch suggestions. Here how it looks like now:

![border-bottom2](https://user-images.githubusercontent.com/3901809/54836849-d34e1200-4ca3-11e9-96e0-377fb2ccd771.gif)

-------------

I have also inserted a `z-index` so the splitters are consistent.


![01](https://user-images.githubusercontent.com/3901809/54836862-d6e19900-4ca3-11e9-8471-5a2ddad60caf.PNG)


![02](https://user-images.githubusercontent.com/3901809/54836863-d77a2f80-4ca3-11e9-9760-bcb46ead3315.PNG)

I had to insert a number 11 on the `z-index`, because of the `.welcomebox` influence, as seen on `WelcomeBox.css:15`:
```css
.welcomebox {
  /* ... */
  font-weight: lighter;
  z-index: 10;
  user-select: none;
}
```

**Comment by janodvarko** [comment]
I can't reproduce this issue on my machine.

Also, Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

If you are still experiencing this issue, please file a bug in Bugzilla, thank you!

Honza
