### ISSUE TITLE
Invalid Background-Color code generate

### ISSUE THREAD

**Issue by vishalksuthar** [firefox-devtools/debugger#8255]
When we change color code using impact element and decrease opacity then  Invalid # color code generate.
Check Bellow screenshot
![image](https://user-images.githubusercontent.com/43471370/63001875-337f6380-be92-11e9-9f00-efe2cc9ab24a.png)

**Comment by nchevobbe** [comment]
Hello Vishal, thanks for filing an issue.
I'm going to close this because this repository is only used for the debugger panel, and you're talking about an inspector one.
Also, I don't think there's an issue with your sreenshot? This is a valid color, with the 2 last character representing the opacity. You can read more about it in https://css-tricks.com/8-digit-hex-codes/
