### ISSUE TITLE
[Theme] TypeScript had black characters with dark theme

### ISSUE THREAD

**Issue by andreiuipath** [firefox-devtools/debugger#8268]
# Steps to reproduce 
Using Firefox Nightly open http://todomvc.com/examples/typescript-angular/#/
Start the DevTools debugger. Set dark theme.
Ctrl + P directives/TodoEscape.ts

# Expected behavior
Curly/round parantheses, "ng.IDirective" and "JQuery" should not be black since it is not visible.

# Actual behavior:
Curly/round parantheses, "ng.IDirective" and "JQuery" is black.
![image](https://user-images.githubusercontent.com/50407920/65579182-ece85300-df7f-11e9-86b3-a9d7d1c83900.png)

**Comment by andreiuipath** [comment]
Seems to be present in the network inspector also.

Visit https://twitter.com/Firefox 

![image](https://user-images.githubusercontent.com/50407920/65580663-c4ae2380-df82-11e9-92b3-2bd2a2270135.png)

**Comment by andreicristianpetcu** [comment]
https://discourse.mozilla.org/t/nightly-dark-mode-brackets-and-dot-not-visible-in-the-dev-tools/45797

**Comment by andreicristianpetcu** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1584074

**Comment by andreiuipath** [comment]
8:09.62 INFO: No more inbound revisions, bisection finished.
 8:09.62 INFO: Last good revision: 9f2ff84ff3eef50321fe9525c6510e6462f519f0
 8:09.62 INFO: First bad revision: 0e9caca3bcf6adf462ea5174be3f9d15ffe77b4c
 8:09.62 INFO: Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=9f2ff84ff3eef50321fe9525c6510e6462f519f0&tochange=0e9caca3bcf6adf462ea5174be3f9d15ffe77b4c

**Comment by janodvarko** [comment]
This seems to be fixed in the lastet Nightly Fx81
![image](https://user-images.githubusercontent.com/37785/91040400-7c720800-e60e-11ea-883e-d5bc8cb93fef.png)

I am closing the report , but please feel free to file a new one.
Note that we moved bug tracking to Bugzilla so, use this link to file a new issue
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Thanks,
Honza
