### ISSUE TITLE
[Docs] More inclusive language in the documentation

### ISSUE THREAD

**Issue by carolstran** [firefox-devtools/debugger#8272]
:wave: I noticed that there are a couple of instances of words "easily" and "just" in your documentation. Unfortunately, words like this can make people feel frustrated and isolated while reading (myself included, hence the issue) - especially if they are facing issues.

If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing instances of "simply", "easy", "just", etc. I use the debugger often, so I'm happy to help 😊  

Also if you're interested or want more information on this topic, I'd highly recommend watching Jim Fisher's [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) talk from Write the Docs Prague 2018 ✍️ 🤓 

Thank you for the work you do and please let me know if you need more details!

**Comment by nchevobbe** [comment]
Hello @carolstran , thanks for opening this issue.
This repo will be soon be made read-only because we are now using the "official" Firefox dev workflow.
We have documentation about this workflow at http://docs.firefox-dev.tools/getting-started/ , and we also have "simply", "just",… instances there as well (see https://searchfox.org/mozilla-central/search?q=(just%7Csimple%7Csimply%7Ceasy)&case=false&regexp=true&path=devtools%2Fdocs%2F).

So I duplicated this issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1597195 , and if you still want to help with this effort, that would be awesome.

**Comment by loganfsmyth** [comment]
Closing in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1597195
